services:
  - type: web
    name: angelim-backend
    runtime: node
    plan: free
    region: ohio
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 3333
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_5gVqFJ3NRyvK@ep-solitary-river-ach3x8za-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require
      - key: TARGET_PHONE
        value: 5595991363678
