import fs from 'fs';
import path from 'path';

const root=process.cwd();
const read=f=>fs.readFileSync(path.join(root,f),'utf8');
const write=(f,s)=>fs.writeFileSync(path.join(root,f),s,'utf8');
function once(src,needle,repl,label){if(!src.includes(needle))throw new Error(`Patch37 bloco2: trecho ausente em ${label}`);return src.replace(needle,repl);}

// ── Backend: catálogo e orientação de upgrade ────────────────────────────────
let plans=read('api/_plans.js');
plans=plans.replace("  notas: 'Notas / NF-e / OCR',","  notas: 'Notas / NF-e',");
plans=plans.replace("  orcamentos: 'Orçamentos / SINAPI',","  orcamentos: 'Orçamentos',");
if(!plans.includes('export const PAID_PLAN_ORDER')){
  const anchor="export function normalizePlan(plan) {\n";
  const helpers=`export const PAID_PLAN_ORDER = Object.freeze(['starter','pro','unlimited']);\n\nexport function minimumPlanForModule(module) {\n  const key=String(module||'').trim();\n  return PAID_PLAN_ORDER.find(plan => PLAN_RULES[plan].modules.includes(key)) || null;\n}\n\nexport function minimumPlanForFeature(feature) {\n  const key=String(feature||'').trim();\n  return PAID_PLAN_ORDER.find(plan => Boolean(PLAN_RULES[plan].features?.[key])) || null;\n}\n\nexport function minimumPlanForUsers(userCount) {\n  const needed=Math.max(1, Number(userCount||1));\n  return PAID_PLAN_ORDER.find(plan => PLAN_RULES[plan].maxUsers == null || PLAN_RULES[plan].maxUsers >= needed) || null;\n}\n\nexport function upgradeDescriptor(requiredPlan) {\n  const rule=requiredPlan ? PLAN_RULES[requiredPlan] : null;\n  return {\n    requiredPlan: rule?.id || null,\n    requiredPlanLabel: rule?.label || 'Plano sob consulta',\n    upgradePath: '/app/planos'\n  };\n}\n\n`;
  plans=once(plans,anchor,helpers+anchor,'_plans helpers');
}
const oldPlanError=/export function planError\(feature, plan\) \{[\s\S]*?\n\}\n\nexport function planModuleError\(module, plan\) \{[\s\S]*?\n\}/;
if(!oldPlanError.test(plans)) throw new Error('Patch37 bloco2: planError/planModuleError não encontrados.');
plans=plans.replace(oldPlanError,`export function planError(feature, plan) {\n  const rule = getPlanRule(plan);\n  const names = {\n    ocr: 'Leitura OCR com IA',\n    signatures: 'Assinatura eletrônica com validação',\n    sinapi: 'SINAPI / Caixa',\n    engineering: 'Controles avançados de engenharia',\n    advancedPermissions: 'Permissões avançadas por módulo'\n  };\n  const requiredPlan=minimumPlanForFeature(feature);\n  const upgrade=upgradeDescriptor(requiredPlan);\n  const resource=names[feature] || 'Este recurso';\n  const message=requiredPlan\n    ? \`${'${resource}'} está disponível a partir do ${'${upgrade.requiredPlanLabel}'}. Seu ${'${rule.label}'} continua ativo normalmente.\`\n    : \`${'${resource}'} não está disponível na contratação atual. Fale com o Suporte / Comercial.\`;\n  return {\n    success:false,\n    code:'PLAN_FEATURE_LOCKED',\n    legacyCode:'PLAN_FEATURE_REQUIRED',\n    feature,\n    plan:rule.id,\n    currentPlan:rule.id,\n    ...upgrade,\n    userMessage:message,\n    error:message\n  };\n}\n\nexport function planModuleError(module, plan) {\n  const rule = getPlanRule(plan);\n  const name = PLAN_MODULE_CATALOG[module] || 'Este módulo';\n  const requiredPlan=minimumPlanForModule(module);\n  const upgrade=upgradeDescriptor(requiredPlan);\n  const message=requiredPlan\n    ? \`${'${name}'} está disponível a partir do ${'${upgrade.requiredPlanLabel}'}. Você pode continuar usando os demais módulos do ${'${rule.label}'}.\`\n    : \`${'${name}'} não está disponível na contratação atual. Fale com o Suporte / Comercial.\`;\n  return {\n    success:false,\n    code:'PLAN_MODULE_LOCKED',\n    legacyCode:'PLAN_MODULE_REQUIRED',\n    module,\n    plan:rule.id,\n    currentPlan:rule.id,\n    ...upgrade,\n    userMessage:message,\n    error:message\n  };\n}`);
write('api/_plans.js',plans);

let users=read('api/users.js');
users=users.replace("import { getPlanRule } from './_plans.js';","import { getPlanRule, minimumPlanForUsers, upgradeDescriptor } from './_plans.js';");
const oldLimit=`function planUserLimitError(usage) {\n  return {\n    success:false,\n    code:'PLAN_USER_LIMIT',\n    plan:usage.planId,\n    limit:usage.maxUsers,\n    current:usage.activeUsers,\n    error:\`Seu time chegou ao limite do \${usage.planLabel}. Este plano inclui \${usage.maxUsers} usuário(s) ativo(s). Para adicionar outra pessoa, gerencie os usuários atuais ou consulte um plano com mais acessos.\`\n  };\n}`;
const newLimit=`function planUserLimitError(usage) {\n  const requiredPlan=minimumPlanForUsers(Number(usage.activeUsers||0)+1);\n  const upgrade=upgradeDescriptor(requiredPlan);\n  const message=\`Seu time chegou ao limite do \${usage.planLabel}. Este plano inclui \${usage.maxUsers} usuário(s) ativo(s). Para adicionar outra pessoa, desative um acesso sem uso ou conheça \${upgrade.requiredPlanLabel}.\`;\n  return {\n    success:false,\n    code:'PLAN_USER_LIMIT',\n    plan:usage.planId,\n    currentPlan:usage.planId,\n    limit:usage.maxUsers,\n    current:usage.activeUsers,\n    ...upgrade,\n    userMessage:message,\n    error:message\n  };\n}`;
if(!users.includes(oldLimit)) throw new Error('Patch37 bloco2: planUserLimitError não encontrado.');
users=users.replace(oldLimit,newLimit);
write('api/users.js',users);

// ── Frontend: Conta & Assinatura vira hub da conta ──────────────────────────
let cob=read('js/cobranca.js');
if(!cob.includes('MODULE_MIN_PLAN:')){
  cob=once(cob,"  PLANOS: {\n",`  MODULE_MIN_PLAN: Object.freeze({ precompras:'pro', contratos:'pro', notas:'pro', orcamentos:'pro', documentos:'pro', assinatura:'pro' }),\n  FEATURE_MIN_PLAN: Object.freeze({ ocr:'pro', signatures:'pro', sinapi:'unlimited', engineering:'unlimited', advancedPermissions:'unlimited' }),\n\n  PLANOS: {\n`,'cobranca plan maps');
}
const oldGo="  goToPlans() { if (typeof Utils!=='undefined') Utils.closeModal?.(); if (typeof App!=='undefined') App.navigate('planos'); setTimeout(()=>this.switchAccountTab('planos'),30); },\n";
if(!cob.includes('openSettingsTab(tab)')){
  cob=once(cob,oldGo,`${oldGo}\n  _planLabel(id) { return this.PLANOS?.[id]?.nome || (id==='trial'?'Teste gratuito':'outro plano'); },\n\n  openSettingsTab(tab) {\n    if (typeof Utils!=='undefined') Utils.closeModal?.();\n    if (typeof App!=='undefined') App.navigate('configuracoes');\n    setTimeout(()=>{ if(typeof Configuracoes!=='undefined') Configuracoes._switch?.(tab); },80);\n  },\n\n  openSupport() {\n    if (typeof Utils!=='undefined') Utils.closeModal?.();\n    if (typeof Suporte!=='undefined' && typeof Suporte.toggleDropdown==='function') Suporte.toggleDropdown();\n  },\n\n  showPlanAccessError(payload={}) {\n    const code=String(payload.code||'');\n    if(code==='PLAN_USER_LIMIT') { if(typeof Configuracoes!=='undefined') Configuracoes.showUserLimitModal?.(payload); return true; }\n    if(!code.startsWith('PLAN_')) return false;\n    const required=payload.requiredPlanLabel || this._planLabel(payload.requiredPlan);\n    const title=payload.module ? 'Módulo disponível em outro plano' : 'Recurso disponível em outro plano';\n    const message=payload.userMessage || payload.error || (required ? \`Disponível a partir do \${required}.\` : 'Fale com o Suporte / Comercial para conhecer as opções.');\n    Utils.showModal(\`<div class="modal" style="max-width:520px"><div class="modal-header"><span class="modal-title">🔒 \${Utils.escapeHtml(title)}</span><button class="modal-close" data-fb-click="Utils.closeModal" data-fb-click-n="0">✕</button></div><div class="modal-body"><p class="plan-locked-copy">\${Utils.escapeHtml(message)}</p>\${required?\`<div style="margin-top:14px;padding:12px;border:1px solid rgba(201,162,39,.28);background:rgba(201,162,39,.07);border-radius:10px"><strong>Plano indicado:</strong> \${Utils.escapeHtml(required)}</div>\`:''}</div><div class="modal-footer"><button class="btn btn-secondary" data-fb-click="Utils.closeModal" data-fb-click-n="0">Continuar no sistema</button><button class="btn btn-primary" data-fb-click="Cobranca.goToPlans" data-fb-click-n="0">Conhecer planos</button></div></div>\`);\n    return true;\n  },\n`,'cobranca account actions');
}

const lockedModule=/  showLockedModule\(routeOrModule\) \{[\s\S]*?\n  \},\n\n\n  isFeatureAllowed/;
if(!lockedModule.test(cob)) throw new Error('Patch37 bloco2: showLockedModule não encontrado.');
cob=cob.replace(lockedModule,`  showLockedModule(routeOrModule) {\n    const module = Auth?.ROUTE_MODULES?.[String(routeOrModule||'')] || String(routeOrModule||'');\n    const labels={precompras:'Pré-Compras',contratos:'Contratos',notas:'Notas / NF-e',orcamentos:'Orçamentos',documentos:'Documentos',assinatura:'Assinatura eletrônica'};\n    const name=labels[module] || (App?.routeMeta?.[routeOrModule]?.label) || 'Este módulo';\n    const p=Auth?.getPlanAccess?.() || {};\n    const requiredId=this.MODULE_MIN_PLAN[module] || null;\n    const required=this._planLabel(requiredId);\n    const current=p.label || 'seu plano atual';\n    Utils.showModal(\`<div class="modal" style="max-width:520px"><div class="modal-header"><span class="modal-title">🔒 Módulo disponível em outro plano</span><button class="modal-close" data-fb-click="Utils.closeModal" data-fb-click-n="0">✕</button></div><div class="modal-body"><h3 style="margin:0 0 8px">\${Utils.escapeHtml(name)}</h3><p class="plan-locked-copy">O <strong>\${Utils.escapeHtml(current)}</strong> continua ativo normalmente. \${requiredId?\`Este módulo está disponível a partir do <strong>\${Utils.escapeHtml(required)}</strong>.\`:'Consulte o Suporte / Comercial para liberar este módulo.'} Nenhum dado foi perdido.</p></div><div class="modal-footer"><button class="btn btn-secondary" data-fb-click="Utils.closeModal" data-fb-click-n="0">Continuar no sistema</button><button class="btn btn-primary" data-fb-click="Cobranca.goToPlans" data-fb-click-n="0">Conhecer planos</button></div></div>\`);\n  },\n\n\n  isFeatureAllowed`);

const lockedFeature=/  showLockedFeature\(feature, title, description='Este recurso não faz parte do plano atual\.'\) \{[\s\S]*?\n  \},\n\n  renderTelaPlanos/;
if(!lockedFeature.test(cob)) throw new Error('Patch37 bloco2: showLockedFeature não encontrado.');
cob=cob.replace(lockedFeature,`  showLockedFeature(feature, title, description='Este recurso não faz parte do plano atual.') {\n    if(this.isFeatureAllowed(feature)) return true;\n    const p=Auth?.getPlanAccess?.()||{};\n    const requiredId=this.FEATURE_MIN_PLAN[feature] || null;\n    const required=this._planLabel(requiredId);\n    const extra=requiredId ? \` Disponível a partir do \${required}.\` : ' Consulte o Suporte / Comercial.';\n    Utils.showModal(\`<div class="modal" style="max-width:520px"><div class="modal-header"><span class="modal-title">🔒 Recurso disponível em outro plano</span><button class="modal-close" data-fb-click="Utils.closeModal" data-fb-click-n="0">✕</button></div><div class="modal-body"><h3 style="margin:0 0 8px">\${Utils.escapeHtml(title)}</h3><p class="plan-locked-copy">\${Utils.escapeHtml(description + extra)} O <strong>\${Utils.escapeHtml(p.label||'seu plano')}</strong> continua ativo normalmente e nenhum dado foi perdido.</p></div><div class="modal-footer"><button class="btn btn-secondary" data-fb-click="Utils.closeModal" data-fb-click-n="0">Continuar</button><button class="btn btn-primary" data-fb-click="Cobranca.goToPlans" data-fb-click-n="0">Conhecer planos</button></div></div>\`);\n    return false;\n  },\n\n  renderTelaPlanos`);

// Tabs do hub: visão, cobrança, meu plano, equipe/sessões, suporte, comparação de planos.
const tabsRegex=/<div class="acc-tabs">[\s\S]*?<\/div>\n      <section class="acc-panel active"[\s\S]*?<section class="acc-panel" data-panel="planos">[\s\S]*?<\/section>/;
if(!tabsRegex.test(cob)) throw new Error('Patch37 bloco2: tabs da Conta & Assinatura não encontradas.');
cob=cob.replace(tabsRegex,`<div class="acc-tabs"><button class="acc-tab active" data-tab="visao" data-fb-click="Cobranca.switchAccountTab" data-fb-click-n="1" data-fb-click-t0="string" data-fb-click-v0="visao">Visão geral</button><button class="acc-tab" data-tab="cobrancas" data-fb-click="Cobranca.switchAccountTab" data-fb-click-n="1" data-fb-click-t0="string" data-fb-click-v0="cobrancas">Cobranças</button><button class="acc-tab" data-tab="modulos" data-fb-click="Cobranca.switchAccountTab" data-fb-click-n="1" data-fb-click-t0="string" data-fb-click-v0="modulos">Meu Plano</button><button class="acc-tab" data-tab="equipe" data-fb-click="Cobranca.switchAccountTab" data-fb-click-n="1" data-fb-click-t0="string" data-fb-click-v0="equipe">Equipe & Sessões</button><button class="acc-tab" data-tab="suporte" data-fb-click="Cobranca.switchAccountTab" data-fb-click-n="1" data-fb-click-t0="string" data-fb-click-v0="suporte">Suporte</button><button class="acc-tab" data-tab="planos" data-fb-click="Cobranca.switchAccountTab" data-fb-click-n="1" data-fb-click-t0="string" data-fb-click-v0="planos">Comparar Planos</button></div>\n      <section class="acc-panel active" data-panel="visao"><div id="finobra-plan-usage" class="card">Consultando uso atual…</div></section>\n      <section class="acc-panel" data-panel="cobrancas"><div id="finobra-billing-history" class="card">Consultando cobranças…</div></section>\n      <section class="acc-panel" data-panel="modulos"><div id="finobra-module-list" class="card">Consultando módulos contratados…</div></section>\n      <section class="acc-panel" data-panel="equipe"><div id="finobra-account-team" class="card">Consultando equipe…</div></section>\n      <section class="acc-panel" data-panel="suporte"><div id="finobra-account-support" class="card">Consultando suporte…</div></section>\n      <section class="acc-panel" data-panel="planos"><div class="acc-mobile-hint">Deslize para o lado para comparar os planos.</div><div class="acc-plans">\${Object.values(this.PLANOS).map(p=>this._renderCardPlano(p,ass.planoId===p.id,canManage)).join('')}</div></section>`);

cob=cob.replace("      this._renderBillingHistory(json.invoices||[]); this._renderModules(p);","      this._renderBillingHistory(json.invoices||[]); this._renderModules(p); this._renderAccountTeam(p); this._renderAccountSupport(p);");
if(!cob.includes('_renderAccountTeam(p) {')){
  const anchor="  _renderBillingHistory(invoices=[]) {\n";
  const methods=`  _renderAccountTeam(p) {\n    const el=document.getElementById('finobra-account-team'); if(!el)return;\n    const active=Number(p?.usage?.activeUsers||0); const max=p?.maxUsers==null?'Ilimitados':Number(p.maxUsers||0);\n    const role=String(Auth?.getUser?.()?.perfil||'').toLowerCase(); const admin=['admin','superadmin'].includes(role);\n    el.innerHTML=\`<div style="font-weight:900;font-size:1rem;margin-bottom:8px">Equipe & Sessões</div><p style="font-size:.8rem;color:var(--text3);line-height:1.55;margin:0 0 16px"><strong style="color:var(--text2)">Usuário é pessoa; sessão é dispositivo.</strong> Notebook, celular e navegadores da mesma pessoa aparecem como sessões de segurança e não aumentam o consumo do plano.</p><div class="acc-usage-grid" style="grid-template-columns:repeat(2,minmax(0,1fr));margin-bottom:16px"><div class="acc-kpi"><div class="acc-kpi-l">Usuários ativos</div><div class="acc-kpi-v">\${active} / \${max}</div></div><div class="acc-kpi"><div class="acc-kpi-l">Permissões avançadas</div><div class="acc-kpi-v">\${p?.features?.advancedPermissions?'Incluídas':'Por perfil'}</div></div></div><div style="display:flex;gap:8px;flex-wrap:wrap">\${admin?'<button class="btn btn-primary" data-fb-click="Cobranca.openSettingsTab" data-fb-click-n="1" data-fb-click-t0="string" data-fb-click-v0="usuarios">Gerenciar usuários</button>':''}<button class="btn btn-secondary" data-fb-click="Cobranca.openSettingsTab" data-fb-click-n="1" data-fb-click-t0="string" data-fb-click-v0="sessoes">Ver sessões e dispositivos</button></div>\`;\n  },\n\n  _renderAccountSupport(p) {\n    const el=document.getElementById('finobra-account-support'); if(!el)return;\n    const level=Utils.escapeHtml(p?.supportLevel||'Padrão');\n    el.innerHTML=\`<div style="font-weight:900;font-size:1rem;margin-bottom:8px">Suporte / Comercial</div><p style="font-size:.82rem;color:var(--text3);line-height:1.55">Seu plano possui atendimento <strong style="color:var(--text2)">\${level}</strong>. Para dúvidas de uso, problemas técnicos ou informações comerciais, use a central do FinObra. Diagnósticos internos ficam restritos à equipe DEV.</p><button class="btn btn-primary" data-fb-click="Cobranca.openSupport" data-fb-click-n="0">Abrir atendimento</button>\`;\n  },\n\n`;
  cob=once(cob,anchor,methods+anchor,'cobranca account team/support');
}
write('js/cobranca.js',cob);

// Usuários: botão realmente navega para a gestão, e payloads de plano usam modal comum.
let cfg=read('js/configuracoes.js');
cfg=cfg.replace('<button class="btn btn-secondary" data-fb-click="Utils.closeModal" data-fb-click-n="0">Gerenciar usuários</button><button class="btn btn-primary" data-fb-click="Cobranca.goToPlans" data-fb-click-n="0">Ver planos</button>','<button class="btn btn-secondary" data-fb-click="Cobranca.openSettingsTab" data-fb-click-n="1" data-fb-click-t0="string" data-fb-click-v0="usuarios">Gerenciar usuários</button><button class="btn btn-primary" data-fb-click="Cobranca.goToPlans" data-fb-click-n="0">Ver planos</button>');
write('js/configuracoes.js',cfg);

// Revarre CSP depois das novas ações do Bloco 2.
const eventNames='click|change|input|submit|mouseover|mouseout|mouseenter|mouseleave|keydown|keyup|keypress|focus|blur|dblclick|contextmenu|pointerdown|pointerup|mousedown|mouseup|touchstart|touchend|dragstart|drop';
const re=new RegExp(`data-fb-(?:${eventNames})=["']([^"']+)["']`,'g');
const files=[...fs.readdirSync(root).filter(x=>x.endsWith('.html')).map(x=>path.join(root,x)),...fs.readdirSync(path.join(root,'js')).filter(x=>x.endsWith('.js')&&x!=='patch26-events.js').map(x=>path.join(root,'js',x))];
const used=new Set(); for(const f of files){const s=fs.readFileSync(f,'utf8');for(const m of s.matchAll(re))used.add(m[1]);}
let bridge=read('js/patch26-events.js'); const match=bridge.match(/const ALLOWED = new Set\((\[[\s\S]*?\])\);/); if(!match)throw new Error('Patch37 bloco2: allowlist CSP ausente.');
const allowed=JSON.parse(match[1]); const merged=[...new Set([...allowed,...used])].sort(); bridge=bridge.replace(match[0],`const ALLOWED = new Set(${JSON.stringify(merged)});`); write('js/patch26-events.js',bridge);

// Teste permanente do bloco.
write('scripts/test-patch37-block2-static.js',`import fs from 'fs';\nfunction a(c,m){if(!c){console.error('❌ '+m);process.exit(1)}console.log('✅ '+m)}\nconst plans=fs.readFileSync('api/_plans.js','utf8');\nconst users=fs.readFileSync('api/users.js','utf8');\nconst cob=fs.readFileSync('js/cobranca.js','utf8');\nconst cfg=fs.readFileSync('js/configuracoes.js','utf8');\na(plans.includes("code:'PLAN_FEATURE_LOCKED'")&&plans.includes("legacyCode:'PLAN_FEATURE_REQUIRED'")&&plans.includes('requiredPlanLabel'),'Feature locks informam plano mínimo sem perder compatibilidade.');\na(plans.includes("code:'PLAN_MODULE_LOCKED'")&&plans.includes("legacyCode:'PLAN_MODULE_REQUIRED'")&&plans.includes('minimumPlanForModule'),'Module locks possuem orientação central de upgrade.');\na(plans.includes("notas: 'Notas / NF-e'")&&plans.includes("orcamentos: 'Orçamentos'")&&!plans.includes("orcamentos: 'Orçamentos / SINAPI'"),'Catálogo separa módulos de features avançadas.');\na(users.includes('minimumPlanForUsers')&&users.includes('requiredPlanLabel')&&users.includes("code:'PLAN_USER_LIMIT'"),'Limite de usuários informa próximo plano compatível.');\na(cob.includes('Equipe & Sessões')&&cob.includes('finobra-account-team')&&cob.includes('_renderAccountTeam'),'Conta & Assinatura reúne equipe e sessões.');\na(cob.includes('Suporte / Comercial')&&cob.includes('_renderAccountSupport')&&cob.includes('openSupport()'),'Conta & Assinatura integra suporte sem diagnóstico de cliente.');\na(cob.includes('showPlanAccessError')&&cob.includes('requiredPlanLabel'),'Frontend possui tradutor amigável de bloqueios de plano.');\na(cob.includes('MODULE_MIN_PLAN')&&cob.includes('FEATURE_MIN_PLAN'),'Bloqueios locais informam plano mínimo esperado.');\na(cfg.includes('Cobranca.openSettingsTab')&&cfg.includes('Dispositivo não é usuário'),'Usuários e sessões têm navegação correta e regra de licenciamento clara.');\nconsole.log('\\n✅ Patch 37 bloco 2 validado.');\n`);
let all=read('scripts/test-static-all.js'); if(!all.includes("'scripts/test-patch37-block2-static.js'")){all=all.replace("  'scripts/test-patch37-static.js',\n","  'scripts/test-patch37-static.js',\n  'scripts/test-patch37-block2-static.js',\n");write('scripts/test-static-all.js',all);}
console.log('✅ Patch 37 bloco 2 aplicado: planos, upgrades, equipe/sessões e suporte consolidados.');
