// PATCH 51 — Workflow de obras multiplexado em /api/audit.
import { neon } from '@neondatabase/serverless';
import { resolveAuthAndTenant } from './_auth.js';
import { canAccessModule, canWriteData, permissionError, normalizeRole } from './_permissions.js';
import { writeAudit } from './_audit.js';

const sqlClient=()=>{if(!process.env.DATABASE_URL)throw new Error('DATABASE_URL não configurada.');return neon(process.env.DATABASE_URL)};
const text=(v,m=255)=>String(v??'').replace(/\0/g,'').trim().slice(0,m);
const id=(v,m=80)=>text(v,m).replace(/[^A-Za-z0-9_.:@-]/g,'');
const date=v=>/^\d{4}-\d{2}-\d{2}$/.test(String(v||''))?String(v):null;
const manager=a=>['superadmin','admin','gestor'].includes(normalizeRole(a?.user?.perfil));
const actor=a=>id(a?.user?.userId||a?.user?.id,64);
const rtRole=p=>/(engenh|arquitet|responsavel.?tecn|responsável.?técn)/i.test(String(p||''));
function payload(v){if(!v||typeof v!=='object'||Array.isArray(v))return{};const o={};for(const[k,x]of Object.entries(v).slice(0,80)){const n=text(k,80).replace(/[^A-Za-z0-9_.-]/g,'');if(!n)continue;if(x===null||['boolean','number'].includes(typeof x))o[n]=x;else if(typeof x==='string')o[n]=x.slice(0,2000)}return o}
function stage(x,n){const eid=id(x?.id||x?.etapa_id);if(!eid)return null;return{etapa_id:eid,ordem:n,codigo:text(x?.codigo,40),nome:text(x?.nome||`Etapa ${n+1}`,240),descricao:text(x?.descricao,4000),tipo:text(x?.tipo,40),tipo_label:text(x?.tipoLabel||x?.tipo_label,80),icone:text(x?.icone,24),dias_sla:Math.max(1,Math.min(365,parseInt(x?.dias_sla,10)||30)),responsavel_user_id:id(x?.responsavel_user_id,64)||null,responsavel_nome:text(x?.responsavel_nome,255)||null,responsavel_perfil:text(x?.responsavel_perfil,64)||null,observacoes:text(x?.observacoes,4000),payload:payload(x?.payload)}}
function clauses(v){return Array.isArray(v)?v.slice(0,100).map((x,n)=>({id:id(x?.id||`cl_${n+1}`)||`cl_${n+1}`,secao:text(x?.secao,120),numero:text(x?.numero||`CLÁUSULA ${n+1}`,80),titulo:text(x?.titulo,300),texto:text(x?.texto,12000)})).filter(x=>x.titulo||x.texto):[]}
async function obra(sql,t,o){const r=await sql`SELECT id,nome,data_inicio FROM obras WHERE tenant_id=${t} AND id=${id(o,64)} LIMIT 1`;return r[0]||null}
async function user(sql,t,u,{technical=false}={}){if(!u)return null;const r=await sql`SELECT id,nome,perfil,ativo FROM usuarios WHERE tenant_id=${t} AND id=${id(u,64)} AND ativo=TRUE LIMIT 1`;const x=r[0]||null;return technical&&x&&!rtRole(x.perfil)?null:x}
async function forecast(sql,t,o){const r=await sql`SELECT x.data_inicio,COALESCE(SUM(w.dias_sla),0)::int total_dias FROM obras x LEFT JOIN workflow_etapas w ON w.tenant_id=x.tenant_id AND w.obra_id=x.id WHERE x.tenant_id=${t} AND x.id=${o} GROUP BY x.data_inicio`;const b=r[0],total=Number(b?.total_dias||0);if(!b?.data_inicio)return{total_dias:total,data_previsao:null};const u=await sql`UPDATE obras SET data_previsao=(${b.data_inicio}::date+${total}::int) WHERE tenant_id=${t} AND id=${o} RETURNING data_previsao`;return{total_dias:total,data_previsao:u[0]?.data_previsao||null}}
function schemaErr(e){return/relation .* does not exist|function finobra_complete_workflow_stage|column .* does not exist/i.test(String(e?.message||''))}

export default async function workflowHandler(req,res){
 const auth=await resolveAuthAndTenant(req);if(!auth.authenticated)return res.status(auth.status||401).json({success:false,error:auth.error||'Acesso não autorizado.'});
 if(!canAccessModule(auth,'obras','read'))return res.status(403).json(permissionError('MODULE_READ_FORBIDDEN','obras'));
 const t=auth.tenantId,sql=sqlClient(),action=text(req.query?.action||req.body?.action,80).toLowerCase(),b=req.body||{},uid=actor(auth);
 try{
  if(req.method==='GET'&&action==='meta_list'){const r=await sql`SELECT * FROM obra_cadastro_geral WHERE tenant_id=${t} ORDER BY updated_at DESC`;return res.json({success:true,data:r})}
  if(req.method==='GET'&&action==='list'){const o=id(req.query?.obraId,64);if(!o||!await obra(sql,t,o))return res.status(404).json({success:false,code:'OBRA_NOT_FOUND',error:'Obra não encontrada.'});const[s,h]=await Promise.all([sql`SELECT * FROM workflow_etapas WHERE tenant_id=${t} AND obra_id=${o} ORDER BY ordem`,sql`SELECT * FROM workflow_historico WHERE tenant_id=${t} AND obra_id=${o} ORDER BY created_at DESC LIMIT 200`]);return res.json({success:true,stages:s,history:h})}
  if(req.method==='GET'&&action==='my'){const r=await sql`SELECT w.*,o.nome obra_nome FROM workflow_etapas w JOIN obras o ON o.tenant_id=w.tenant_id AND o.id=w.obra_id WHERE w.tenant_id=${t} AND w.responsavel_user_id=${uid} AND w.status='em_andamento' ORDER BY w.updated_at,w.ordem`;return res.json({success:true,tasks:r})}
  if(req.method==='GET'&&action==='settings'){const r=await sql`SELECT * FROM tenant_patch51_settings WHERE tenant_id=${t} LIMIT 1`;return res.json({success:true,settings:r[0]||{tenant_id:t,cub_modo:'fixo',cub_valor:0,cub_referencia:null,cub_uf:null,contract_clauses:[]}})}
  if(req.method!=='POST')return res.status(405).json({success:false,error:'Método não permitido.'});
  if(!canWriteData(auth)||!canAccessModule(auth,'obras','write'))return res.status(403).json(permissionError('MODULE_WRITE_FORBIDDEN','obras'));

  if(action==='meta_save'){
   const o=id(b.obraId||b.obra_id,64);if(!await obra(sql,t,o))return res.status(404).json({success:false,code:'OBRA_NOT_FOUND',error:'Obra não encontrada.'});const m=b.meta&&typeof b.meta==='object'?b.meta:b,typ=['interno','externo'].includes(String(m.responsavel_tecnico_tipo))?String(m.responsavel_tecnico_tipo):'externo';let ru=null;
   if(typ==='interno'){ru=await user(sql,t,m.responsavel_tecnico_usuario_id,{technical:true});if(!ru)return res.status(400).json({success:false,code:'INVALID_INTERNAL_RT',error:'Selecione um engenheiro, arquiteto ou responsável técnico interno ativo.'})}
   const p=JSON.stringify(payload(m.payload));const r=await sql`INSERT INTO obra_cadastro_geral(tenant_id,obra_id,rg,orgao_expedidor,data_nascimento,responsavel_tecnico_tipo,responsavel_tecnico_usuario_id,responsavel_tecnico_nome,responsavel_tecnico_registro,subtitulo_capa,payload,updated_at) VALUES(${t},${o},${text(m.rg,64)||null},${text(m.orgao_expedidor,64)||null},${date(m.data_nascimento)},${typ},${ru?.id||null},${typ==='interno'?ru?.nome:text(m.responsavel_tecnico_nome,255)||null},${text(m.responsavel_tecnico_registro,120)||null},${text(m.subtitulo_capa,255)||null},${p}::jsonb,NOW()) ON CONFLICT(tenant_id,obra_id) DO UPDATE SET rg=EXCLUDED.rg,orgao_expedidor=EXCLUDED.orgao_expedidor,data_nascimento=EXCLUDED.data_nascimento,responsavel_tecnico_tipo=EXCLUDED.responsavel_tecnico_tipo,responsavel_tecnico_usuario_id=EXCLUDED.responsavel_tecnico_usuario_id,responsavel_tecnico_nome=EXCLUDED.responsavel_tecnico_nome,responsavel_tecnico_registro=EXCLUDED.responsavel_tecnico_registro,subtitulo_capa=EXCLUDED.subtitulo_capa,payload=EXCLUDED.payload,updated_at=NOW() RETURNING *`;
   await writeAudit(sql,req,auth,{acao:'salvar',entidade:'obra_cadastro_geral',entidadeId:o,depois:{rg:!!r[0]?.rg,responsavel_tecnico_tipo:typ}});return res.json({success:true,meta:r[0]})
  }
  if(action==='initialize'){
   const o=id(b.obraId||b.obra_id,64);if(!await obra(sql,t,o))return res.status(404).json({success:false,code:'OBRA_NOT_FOUND',error:'Obra ainda não foi confirmada na nuvem.'});const old=await sql`SELECT * FROM workflow_etapas WHERE tenant_id=${t} AND obra_id=${o} ORDER BY ordem`;if(old.length)return res.json({success:true,alreadyInitialized:true,stages:old,...await forecast(sql,t,o)});
   const ss=(Array.isArray(b.stages)?b.stages:[]).slice(0,100).map(stage).filter(Boolean);if(!ss.length)return res.status(400).json({success:false,code:'WORKFLOW_EMPTY',error:'O workflow precisa de pelo menos uma etapa.'});
   const ids=[...new Set(ss.map(x=>x.responsavel_user_id).filter(Boolean))],us=ids.length?await sql`SELECT id,nome,perfil FROM usuarios WHERE tenant_id=${t} AND ativo=TRUE AND id=ANY(${ids})`:[],um=new Map(us.map(x=>[String(x.id),x]));for(const s of ss){if(s.responsavel_user_id){const u=um.get(String(s.responsavel_user_id));if(!u)return res.status(400).json({success:false,code:'INVALID_WORKFLOW_USER',error:`Responsável inválido na etapa ${s.nome}.`});s.responsavel_nome=u.nome;s.responsavel_perfil=u.perfil}}
   const first=ss[0];if(!first.responsavel_user_id)return res.status(409).json({success:false,code:'WORKFLOW_FIRST_STAGE_UNASSIGNED',error:'Defina o responsável da primeira etapa antes de iniciar o workflow.'});const j=JSON.stringify(ss);
   await sql`INSERT INTO workflow_etapas(tenant_id,obra_id,etapa_id,ordem,codigo,nome,descricao,tipo,tipo_label,icone,dias_sla,status,responsavel_user_id,responsavel_nome,responsavel_perfil,started_at,observacoes,payload) SELECT ${t},${o},x.etapa_id,x.ordem,x.codigo,x.nome,x.descricao,x.tipo,x.tipo_label,x.icone,x.dias_sla,CASE WHEN x.ordem=0 THEN 'em_andamento' ELSE 'pendente' END,x.responsavel_user_id,x.responsavel_nome,x.responsavel_perfil,CASE WHEN x.ordem=0 THEN NOW() ELSE NULL END,x.observacoes,x.payload FROM jsonb_to_recordset(${j}::jsonb) AS x(etapa_id VARCHAR(80),ordem INTEGER,codigo VARCHAR(40),nome VARCHAR(240),descricao TEXT,tipo VARCHAR(40),tipo_label VARCHAR(80),icone VARCHAR(24),dias_sla INTEGER,responsavel_user_id VARCHAR(64),responsavel_nome VARCHAR(255),responsavel_perfil VARCHAR(64),observacoes TEXT,payload JSONB) ON CONFLICT(tenant_id,obra_id,etapa_id) DO NOTHING`;
   await sql`INSERT INTO workflow_historico(tenant_id,obra_id,etapa_id,evento,actor_user_id,responsavel_user_id,detalhes) VALUES(${t},${o},${first.etapa_id},'atribuida',${uid},${first.responsavel_user_id},${JSON.stringify({ordem:0,nome:first.nome,inicial:true})}::jsonb)`;const saved=await sql`SELECT * FROM workflow_etapas WHERE tenant_id=${t} AND obra_id=${o} ORDER BY ordem`;const f=await forecast(sql,t,o);await writeAudit(sql,req,auth,{acao:'criar',entidade:'workflow_obra',entidadeId:o,depois:{etapas:saved.length,total_dias:f.total_dias}});return res.status(201).json({success:true,stages:saved,...f})
  }
  if(action==='complete'){
   const o=id(b.obraId||b.obra_id,64),e=id(b.etapaId||b.etapa_id,80),r=await sql`SELECT * FROM workflow_etapas WHERE tenant_id=${t} AND obra_id=${o} AND etapa_id=${e} LIMIT 1`;if(!r.length)return res.status(404).json({success:false,code:'WORKFLOW_STAGE_NOT_FOUND',error:'Etapa não encontrada.'});const s=r[0];
   if(s.status!=='em_andamento')return res.status(409).json({success:false,code:'WORKFLOW_STAGE_NOT_ACTIVE',error:'Somente a etapa em andamento pode ser concluída.'});if(!s.responsavel_user_id)return res.status(409).json({success:false,code:'WORKFLOW_STAGE_UNASSIGNED',error:'Defina um responsável antes de concluir esta etapa.'});if(String(s.responsavel_user_id)!==uid&&!manager(auth))return res.status(403).json({success:false,code:'WORKFLOW_NOT_ASSIGNED',error:'Esta etapa está atribuída a outro usuário.'});
   const rr=await sql`SELECT finobra_complete_workflow_stage(${t},${o},${e},${uid}) result`,f=await forecast(sql,t,o),result=rr[0]?.result||{};await writeAudit(sql,req,auth,{acao:'concluir',entidade:'workflow_etapa',entidadeId:`${o}:${e}`,antes:{status:s.status,responsavel_user_id:s.responsavel_user_id},depois:{status:'concluido',next_stage:result?.next_stage?.etapa_id||null}});return res.json({success:true,result,...f})
  }
  if(action==='stage_update'){
   if(!manager(auth))return res.status(403).json({success:false,code:'WORKFLOW_MANAGER_REQUIRED',error:'Somente administrador ou gestor pode ajustar SLA e responsável.'});const o=id(b.obraId||b.obra_id,64),e=id(b.etapaId||b.etapa_id,80),r=await sql`SELECT * FROM workflow_etapas WHERE tenant_id=${t} AND obra_id=${o} AND etapa_id=${e} LIMIT 1`;if(!r.length)return res.status(404).json({success:false,code:'WORKFLOW_STAGE_NOT_FOUND',error:'Etapa não encontrada.'});const c=r[0],d=b.dias_sla===undefined?Number(c.dias_sla):parseInt(b.dias_sla,10);if(!Number.isFinite(d)||d<Number(c.dias_sla))return res.status(409).json({success:false,code:'SLA_DECREASE_NOT_ALLOWED',error:'O SLA pode ser mantido ou aumentado, nunca reduzido.'});const hu=Object.prototype.hasOwnProperty.call(b,'responsavel_user_id');let nu=null;if(hu&&b.responsavel_user_id){nu=await user(sql,t,b.responsavel_user_id);if(!nu)return res.status(400).json({success:false,code:'INVALID_WORKFLOW_USER',error:'Responsável inválido.'})}
   const ns=hu?(nu?.id||null):c.responsavel_user_id,nstat=c.status==='bloqueado'&&ns?'em_andamento':c.status;const u=await sql`UPDATE workflow_etapas SET dias_sla=${Math.min(365,d)},responsavel_user_id=${ns},responsavel_nome=${hu?(nu?.nome||null):c.responsavel_nome},responsavel_perfil=${hu?(nu?.perfil||null):c.responsavel_perfil},status=${nstat},started_at=CASE WHEN ${nstat}='em_andamento' THEN COALESCE(started_at,NOW()) ELSE started_at END,observacoes=${b.observacoes===undefined?c.observacoes:text(b.observacoes,4000)},updated_at=NOW() WHERE tenant_id=${t} AND obra_id=${o} AND etapa_id=${e} RETURNING *`;await sql`INSERT INTO workflow_historico(tenant_id,obra_id,etapa_id,evento,actor_user_id,responsavel_user_id,detalhes) VALUES(${t},${o},${e},'ajustada',${uid},${u[0]?.responsavel_user_id||null},${JSON.stringify({dias_sla_anterior:Number(c.dias_sla),dias_sla_novo:Number(u[0]?.dias_sla),responsavel_anterior:c.responsavel_user_id||null})}::jsonb)`;return res.json({success:true,stage:u[0],...await forecast(sql,t,o)})
  }
  if(action==='settings_save'){
   if(!manager(auth))return res.status(403).json({success:false,code:'WORKFLOW_MANAGER_REQUIRED',error:'Somente administrador ou gestor pode alterar CUB e cláusulas gerais.'});const r=await sql`SELECT * FROM tenant_patch51_settings WHERE tenant_id=${t} LIMIT 1`,c=r[0]||{},mode=['fixo','volante'].includes(String(b.cub_modo))?String(b.cub_modo):(c.cub_modo||'fixo'),raw=b.cub_valor===undefined?Number(c.cub_valor||0):Number(b.cub_valor),cub=Number.isFinite(raw)?Math.max(0,Math.min(1000000,raw)):0,cl=b.contract_clauses===undefined?(Array.isArray(c.contract_clauses)?c.contract_clauses:[]):clauses(b.contract_clauses),cj=JSON.stringify(cl);
   const s=await sql`INSERT INTO tenant_patch51_settings(tenant_id,cub_modo,cub_valor,cub_referencia,cub_uf,contract_clauses,updated_at) VALUES(${t},${mode},${cub},${date(b.cub_referencia)||c.cub_referencia||null},${text(b.cub_uf||c.cub_uf,2).toUpperCase()||null},${cj}::jsonb,NOW()) ON CONFLICT(tenant_id) DO UPDATE SET cub_modo=EXCLUDED.cub_modo,cub_valor=EXCLUDED.cub_valor,cub_referencia=EXCLUDED.cub_referencia,cub_uf=EXCLUDED.cub_uf,contract_clauses=EXCLUDED.contract_clauses,updated_at=NOW() RETURNING *`;
   if(b.contract_clauses!==undefined){const vr=await sql`SELECT COALESCE(MAX(versao),0)+1 versao FROM contract_clause_versions WHERE tenant_id=${t}`;await sql`INSERT INTO contract_clause_versions(tenant_id,versao,clauses,created_by) VALUES(${t},${Number(vr[0]?.versao||1)},${cj}::jsonb,${uid})`};return res.json({success:true,settings:s[0]})
  }
  return res.status(400).json({success:false,error:'Ação inválida.'});
 }catch(e){console.error('[Patch51]',e);if(schemaErr(e))return res.status(503).json({success:false,code:'PATCH51_SCHEMA_NOT_READY',error:'Patch 51 aguardando migration de banco.'});if(/SLA_DECREASE_NOT_ALLOWED/.test(String(e?.message)))return res.status(409).json({success:false,code:'SLA_DECREASE_NOT_ALLOWED',error:'O SLA só pode ser aumentado.'});if(/WORKFLOW_STAGE_UNASSIGNED/.test(String(e?.message)))return res.status(409).json({success:false,code:'WORKFLOW_STAGE_UNASSIGNED',error:'Defina um responsável para a etapa.'});return res.status(500).json({success:false,error:'Erro interno no workflow.'})}
}
